# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    public_directory: '%kernel.project_dir%/public/'
    private_directory: '%kernel.project_dir%/documents/'
    config_directory: '%kernel.project_dir%/config/'
    env_file: '%kernel.project_dir%/.env.local'
    app_env: '%env(APP_ENV)%'
    lotys_code_society: '%env(API_LOTYS_CODE_SOCIETY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $publicDirectory: '%public_directory%'
            $privateDirectory: '%private_directory%'
            $configDirectory: '%config_directory%'
            $envFile: '%env_file%'
            $appEnv: '%app_env%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\Api\ApiLotys:
        arguments:
            $urlLotys: '%env(resolve:API_LOTYS_URL)%'
            $username: '%env(resolve:API_LOTYS_USERNAME)%'
            $password: '%env(resolve:API_LOTYS_PASSWORD)%'
